#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'build-essential', '1.1.0'

#cookbook 'nodejs', '0.6.11'

#cookbook 'npm', '0.1.0'

cookbook 'python',
  :git => 'https://github.com/opscode-cookbooks/python',
  :ref => '1.0.8'

cookbook 'tmux', '1.0.0'

cookbook 'vim', '1.0.2'

cookbook 'ruby_build',
  :git => 'https://github.com/fnichol/chef-ruby_build.git',
  :ref => 'v0.6.2'

cookbook 'rbenv',
  :git => 'https://github.com/fnichol/chef-rbenv.git',
  :ref => 'v0.6.10'